<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: sans-serif; font-size: 11px; color: #1f2937; line-height: 1.5; }

        .cover { text-align: center; padding: 120px 40px 40px; page-break-after: always; }
        .cover-logo { font-size: 36px; font-weight: bold; color: #1d4ed8; margin-bottom: 10px; }
        .cover-subtitle { font-size: 14px; color: #6b7280; margin-bottom: 60px; }
        .cover-exam { font-size: 28px; font-weight: bold; color: #111827; margin-bottom: 8px; }
        .cover-plan { font-size: 18px; color: #2563eb; margin-bottom: 40px; }
        .cover-info { font-size: 12px; color: #6b7280; margin-bottom: 5px; }
        .cover-line { width: 60px; height: 3px; background: #2563eb; margin: 30px auto; }

        .page-header { background: #2563eb; color: white; padding: 15px 20px; margin: -20px -20px 20px; }
        .page-header h2 { font-size: 16px; margin: 0; }

        .summary { background: #eff6ff; border-left: 4px solid #2563eb; padding: 12px 16px; margin-bottom: 20px; font-size: 11px; }

        .day-block { margin-bottom: 15px; border: 1px solid #e5e7eb; border-radius: 6px; overflow: hidden; }
        .day-header { background: #f9fafb; padding: 10px 14px; border-bottom: 1px solid #e5e7eb; }
        .day-number { display: inline-block; background: #2563eb; color: white; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; margin-right: 8px; }
        .day-title { font-weight: bold; font-size: 12px; color: #111827; }
        .day-body { padding: 10px 14px; }

        .subject-row { padding: 6px 0; border-bottom: 1px solid #f3f4f6; }
        .subject-row:last-child { border-bottom: none; }
        .subject-name { font-weight: bold; font-size: 11px; color: #1d4ed8; }
        .subject-hours { float: right; color: #6b7280; font-size: 10px; }
        .topics { color: #6b7280; font-size: 10px; margin-top: 2px; }

        .tips-box { background: #fefce8; border: 1px solid #fde68a; padding: 8px 12px; margin-top: 8px; border-radius: 4px; font-size: 10px; color: #92400e; }

        .resources { margin-top: 8px; }
        .resource-item { font-size: 10px; color: #4b5563; padding: 2px 0; }
        .resource-type { display: inline-block; background: #f3f4f6; padding: 1px 6px; border-radius: 3px; font-size: 9px; text-transform: uppercase; margin-right: 4px; }

        .footer { text-align: center; color: #9ca3af; font-size: 9px; margin-top: 30px; padding-top: 10px; border-top: 1px solid #e5e7eb; }

        .page-break { page-break-before: always; }
    </style>
</head>
<body>
    <!-- Cover Page -->
    <div class="cover">
        <div class="cover-logo">SARKARI</div>
        <div class="cover-subtitle">AI-Powered Exam Preparation Blueprint</div>
        <div class="cover-line"></div>
        <div class="cover-exam"><?= htmlspecialchars($blueprint['exam_name']) ?></div>
        <div class="cover-plan"><?= count($days) ?>-Day Success Blueprint</div>
        <div class="cover-line"></div>
        <div class="cover-info"><strong>Prepared for:</strong> <?= htmlspecialchars($user['name']) ?></div>
        <div class="cover-info"><strong>Education:</strong> <?= htmlspecialchars($blueprint['education']) ?></div>
        <div class="cover-info"><strong>Study Hours/Day:</strong> <?= htmlspecialchars($blueprint['study_hours']) ?></div>
        <div class="cover-info"><strong>Exam Date:</strong> <?= date('d M Y', strtotime($blueprint['exam_date'])) ?></div>
        <div class="cover-info"><strong>Generated:</strong> <?= date('d M Y') ?></div>
        <div style="margin-top: 60px;">
            <div class="cover-info" style="font-size: 10px; color: #9ca3af;">
                This blueprint was generated by AI and personalized for your profile.<br>
                Focus areas: <?= htmlspecialchars(implode(', ', json_decode($blueprint['weak_subjects'], true))) ?>
            </div>
        </div>
    </div>

    <!-- Summary -->
    <?php if (!empty($blueprint['summary'])): ?>
    <div class="summary">
        <strong>Strategy Overview:</strong> <?= htmlspecialchars($blueprint['summary']) ?>
    </div>
    <?php endif; ?>

    <!-- Days -->
    <?php foreach ($days as $i => $day): ?>
        <?php if ($i > 0 && $i % 3 === 0): ?>
            <div class="page-break"></div>
        <?php endif; ?>

        <div class="day-block">
            <div class="day-header">
                <span class="day-number">DAY <?= $day['day_number'] ?></span>
                <span class="day-title"><?= htmlspecialchars($day['title']) ?></span>
            </div>
            <div class="day-body">
                <?php $subjects = json_decode($day['subjects_json'], true); ?>
                <?php foreach ($subjects as $sub): ?>
                <div class="subject-row">
                    <span class="subject-name"><?= htmlspecialchars($sub['subject'] ?? '') ?></span>
                    <span class="subject-hours"><?= htmlspecialchars($sub['hours'] ?? '') ?> hours</span>
                    <?php if (!empty($sub['topics'])): ?>
                    <div class="topics">Topics: <?= htmlspecialchars(implode(', ', $sub['topics'])) ?></div>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>

                <?php if (!empty($day['tips'])): ?>
                <div class="tips-box">
                    <strong>Tip:</strong> <?= htmlspecialchars($day['tips']) ?>
                </div>
                <?php endif; ?>

                <?php $resources = json_decode($day['resources'] ?? '[]', true); ?>
                <?php if (!empty($resources)): ?>
                <div class="resources">
                    <?php foreach ($resources as $res): ?>
                    <div class="resource-item">
                        <span class="resource-type"><?= htmlspecialchars($res['type'] ?? 'book') ?></span>
                        <?= htmlspecialchars($res['title'] ?? '') ?>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>

    <div class="footer">
        Generated by Sarkari - AI-Powered Exam Preparation | <?= date('Y') ?> | sarkari.in
    </div>
</body>
</html>
